actions:
  pre:
    Vundlevim-install: [ -e ~/.vim/bundle/Vundle.vim/autoload/vundle.vim ] || git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    Vundle: vim +PluginInstall +qall
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  gen_vimrc:
    dst: ~/.vimrc
    src: vimrc
    action:
  gen_bashrc:
    dst: ~/.bashrc
    src: bashrc

profiles:
  cores:
    dotfiles:
      - gitconfig
      - bash_profile
      - core_vim
      - core_vimrc
      - core_bashrc
      - core_w3m
      - core_tmux
  default:
    dotfiles:
      - vimrc_plug_min
    include:
      - cores
  crystal:
    dotfiles:
      - vimrc_plug_full
      - banner_default
      - hyper_conf
      - hyper
    include:
      - default
  remote:
    dotfiles:
      - banner_remote
    include:
      - default
