actions:
  pre:
    Vundle_install: test -e ~/.vim/bundle/Vundle.vim/autoload/vundle.vim || git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  Vundle: vim +'source $HOME/.vim/plugin/vimrc.plug.installer' +PluginInstall +qall
  source_bashrc: source $HOME/.bashrc
  brew: type brew && brew bundle install --global

config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  bash_profile:
    dst: ~/.bash_profile
    src: bash/bash_profile
    actions:
      - source_bashrc
    link: true

  core_vim_syntax:
    dst: ~/.vim/syntax
    src: vim/syntax
    link: true
  core_vim_template:
    dst: ~/.vim/template
    src: vim/template
    link: true
  core_vim_filetype:
    dst: ~/.vim/filetype.vim
    src: vim/filetype.vim
    link: true
  core_vim_ftdetect:
    dst: ~/.vim/ftdetect
    src: vim/ftdetect
    link: true
  core_vim_dictionary:
    dst: ~/.vim/dictionary
    src: vim/dictionary
    link: true
  core_vim_ftplugin:
    dst: ~/.vim/ftplugin
    src: vim/ftdetect
    link: true
  vimrc:
    dst: ~/.vimrc
    src: vim/vimrcs/vimrc
  core_vimrc:
    dst: ~/.vim/profiles/vimrc.core
    src: vim/vimrcs/vimrc.core
    link: true

  vimrc_plug_installer: # vim plugin installer. plugins in vim_plug_min and vim_plug_full will be installed.
    dst: ~/.vim/plugin/vimrc.plug.installer
    src: vim/vimrcs/vimrc.plug.installer
    link: true
    actions:
      - Vundle_install
      - Vundle
  vim_plug_min:         # minimum vim plugin list
    dst: ~/.vim/profiles/plug.min
    src: vim/vimrcs/plug.min
    link: true
  vim_plug_full:        # full vim plugin list
    dst: ~/.vim/profiles/plug.full
    src: vim/vimrcs/plug.full
    link: true
  vimrc_plug_min:       # configs for vim_plug_min
    dst: ~/.vim/profiles/vimrc.plug.min
    src: vim/vimrcs/vimrc.plug.min
    link: true
  vimrc_plug_full:      # configs for vim_plug_full
    dst: ~/.vim/profiles/vimrc.plug.full
    src: vim/vimrcs/vimrc.plug.full
    link: true

  vim_util_swift-format: # shape up swift code
    dst: ~/.vim/swift-format.py
    src: vim/swift-format.py
    link: true
  vimrc_plug_swift-format: # configs for vim_util_swift-format
    dst: ~/.vim/profiles/vimrc.plug.swift-format
    src: vim/vimrcs/vimrc.plug.swift-format
    link: true
  core_bashrc:
    dst: ~/.bashrc
    src: bash/bashrc
    link: true
  core_w3m:
    dst: ~/.w3m
    src: w3m
  core_tmux:
    dst: ~/.tmux.conf
    src: tmux/tmux.conf
    link: true

  core_ssh:
    dst: ~/.ssh
    src: ssh/ssh

  banner_default:
    dst: ~/.bashrc.banner
    src: bash/bashrc.banner.default
  banner_remote:
    dst: ~/.bashrc.banner
    src: bash/bashrc.banner.remote

  core_brew:
    dst: ~/.Brewfile
    src: brew/Brewfile.core
    actions:
      - brew
  gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  hyper_conf:
    dst: ~/.hyper.js
    src: hyper/hyper.js
    link: true
  wtf_conf:
    dst: ~/.config/wtf/config.yml
    src: wtf.config.yml
    link: true
profiles:
  cores:
    dotfiles:
      - gitconfig
      - bash_profile
      - core_vim_syntax
      - core_vim_template
      - core_vim_filetype
      - core_vim_ftdetect
      - core_vim_ftplugin
      - core_vim_dictionary
      - vimrc
      - core_vimrc
      - core_bashrc
      - core_w3m
      - core_tmux
  default:
    dotfiles:
      - vimrc_plug_installer
      - vim_plug_min
      - vimrc_plug_min
      - vim_util_swift-format
      - vimrc_plug_swift-format
    include:
      - cores
  crystal:
    dotfiles:
      - vim_plug_full
      - vimrc_plug_full
      - banner_default
      - hyper_conf
      - wtf_conf
    include:
      - default
  remote:
    dotfiles:
      - banner_remote
      - core_brew
    include:
      - default
